version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
        - "54321:5432"
    environment:
      POSTGRES_DB: auditlog
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
