version: '3'

services:
  db:
    image: tc-postgres-beta:latest
    restart: always
    container_name: "tc-postgres-db"
    environment:
      POSTGRES_DB: tc-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54322:5432
    build:
      context: .
